language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
libsodium-dev
before_install:
  - sudo apt-get install libsodium-dev
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
