language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - echo "deb http://uk.archive.ubuntu.com/ubuntu/ xenial main restricted" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://uk.archive.ubuntu.com/ubuntu/ xenial-updates main restricted" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install libsodium-dev
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
