language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - echo "deb http://ftp.uk.debian.org/debian/ sid main " | sudo tee -a /etc/apt/sources.list
  - echo "deb-src http://ftp.uk.debian.org/debian/ sid main " | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install libsodium-dev
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
