dist: trusty
sudo: required
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - sudo add-apt-repository ppa:chris-lea/libsodium;
  - sudo echo "deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list;
  - sudo echo "deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list;
  - sudo apt-get update && sudo apt-get install libsodium-dev;
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
